src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $titre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_publication;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="articles")
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="articles")
     */
    private $tags;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDatePublication(): ?\DateTimeInterface
    {
        return $this->date_publication;
    }

    public function setDatePublication(\DateTimeInterface $date_publication): self
    {
        $this->date_publication = $date_publication;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }
}

src/Controller/ArticleCrudController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Repository\ArticleRepository;
use App\Form\ArticleType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class ArticleCrudController extends AbstractController
{
    /**
     * @Route("/articles", name="articles_index")
     */
    public function index(ArticleRepository $repository)
    {
        $articles = $repository->findAll();
        return $this->render('article_crud/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/articles/create", name="articles_create")
     */
    public function create(Request $request){
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);
        dump($article);
        if($form->isSubmitted() && $form->isValid()){
            // Vérifie que le form a bien été envoyé et valide
            // je peux sauvegarder mon utilisateur
            $em = $this->getDoctrine()->getManager();
            $em->persist($article);
            $em->flush();
            return $this->redirectToRoute("articles_read",["article"=>$article->getId()]);
        }
        return $this->render("article_crud/create.html.twig", [
            'myForm'=>$form->createView()
        ]);

    }

    /**
     * @Route("/articles/{article}", name="articles_read")
     */

    public function read(Article $article){

        return $this->render('article_crud/read.html.twig', [
            "article" => $article
        ]);
    }

    /**
     * @Route("/articles/{article}/update", name="articles_update")
     */

    public function update(Article $article, Request $request){
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);
        dump($request);
        if ($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute("articles_read", ["article"=>$article->getId()]);
        }
        return $this->render('article_crud/update.html.twig', [
            "articleForm" => $form->createView()
        ]);
    }



    /**
     * @Route("/articles/{article}/delete", name="articles_delete")
     */

    public function delete(Article $article){

        $em = $this->getDoctrine()->getManager();
        $em ->remove($article);
        $em->flush();
        return $this->redirectToRoute("articles_index");
    }
}

templates/article_crud/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Article creation
{% endblock %}

{% block body %}
    <style>
        @font-face {
            font-family: "Architects Daughter";
            src: url("/fonts/ArchitectsDaughter-Regular.ttf") format("truetype");
        }
        .example-wrapper { margin: 1em auto;
            max-width: 800px; width: 95%;
            font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
            border: 5px solid #34eb95; border-radius: 5px;
        }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }


        a{
            color:black;
        }


        .container{
            max-width:600px;
            margin:auto;
            background: #65b4db;
            padding:20px;
            box-sizing:border-box;
            box-shadow:0px 3px 6px rgba(0, 0, 0, 0.5);
            font-size:16px;
            border:1px solid #444;
            border-radius:3px;
            animation: 1.25s flyin ease;
            margin-top: 20px;
            font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
        }

        @keyframes flyin{
            from{ transform: translateY(100%); opacity:0; }
        }

    </style>
    <div class="container">
        <h1>Création d'Article</h1>
        <a href="{{ path('articles_index') }}">Retour</a>
        {{ form(myForm) }}
    </div>

{% endblock %}

templates/article_crud/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Article{% endblock %}

{% block body %}
<style>
    @font-face {
        font-family: "Architects Daughter";
        src: url("/fonts/ArchitectsDaughter-Regular.ttf") format("truetype");
    }
    .example-wrapper { margin: 1em auto;
        max-width: 800px; width: 95%;
        font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
        border: 5px solid #34eb95; border-radius: 5px;
    }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }


    a{
        color:black;
    }


    .container{
        max-width:600px;
        margin:auto;
        background: #65b4db;
        padding:20px;
        box-sizing:border-box;
        box-shadow:0px 3px 6px rgba(0, 0, 0, 0.5);
        font-size:16px;
        border:1px solid #444;
        border-radius:3px;
        animation: 1.25s flyin ease;
        margin-top: 20px;
        font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
    }

    li {
        list-style-type: none;
    }

    @keyframes flyin{
        from{ transform: translateY(100%); opacity:0; }
    }

</style>

<div class="container">
    <h1>Tous mes articles ✅</h1>
    <ul>
        {% for article in articles %}
            <li><a href="{{ path('articles_read', {'article': article.id}) }}">{{ article.titre }}</a></li>
        {% endfor %}
    </ul>

    <a href="{{ path('articles_create') }}">Créer un article</a>


</div>
{% endblock %}

templates/article_crud/read.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <style>
        @font-face {
            font-family: "Architects Daughter";
            src: url("/fonts/ArchitectsDaughter-Regular.ttf") format("truetype");
        }
        .example-wrapper { margin: 1em auto;
            max-width: 800px; width: 95%;
            font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
            border: 5px solid #34eb95; border-radius: 5px;
        }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }


        a{
            color:black;
        }


        .container{
            max-width:600px;
            margin:auto;
            background: #65b4db;
            padding:20px;
            box-sizing:border-box;
            box-shadow:0px 3px 6px rgba(0, 0, 0, 0.5);
            font-size:16px;
            border:1px solid #444;
            border-radius:3px;
            animation: 1.25s flyin ease;
            margin-top: 20px;
            font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
        }

        .crud{
            position: relative;
            display: flex;
            flex-direction: column;
            align-content: flex-start;
        }

        @keyframes flyin{
            from{ transform: translateY(100%); opacity:0; }
        }

    </style>
    <div class="container">
    <h1> {{ article.titre }}</h1>
    <h2> {{ article.datePublication | date("d/m/Y H:i") }}</h2>
    <h2> {{ article.contenu }}</h2>
    </div>
    <div class="crud">
    <a href="{{ path('articles_update', {"article": article.id}) }}">Modifier</a>
    <a href="{{ path('articles_delete', {"article": article.id}) }}">Supprimer</a>
    </div>
{% endblock %}

{% block title %}

        Article {{ article.titre }}



{% endblock %}

templates/article_crud/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Article modification
{% endblock %}

{% block body %}
    <style>
        @font-face {
            font-family: "Architects Daughter";
            src: url("/fonts/ArchitectsDaughter-Regular.ttf") format("truetype");
        }
        .example-wrapper { margin: 1em auto;
            max-width: 800px; width: 95%;
            font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
            border: 5px solid #34eb95; border-radius: 5px;
        }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }


        a{
            color:black;
        }


        .container{
            max-width:600px;
            margin:auto;
            background: #65b4db;
            padding:20px;
            box-sizing:border-box;
            box-shadow:0px 3px 6px rgba(0, 0, 0, 0.5);
            font-size:16px;
            border:1px solid #444;
            border-radius:3px;
            animation: 1.25s flyin ease;
            margin-top: 20px;
            font: 18px/1.5 sans-serif; font-family: "Architects Daughter";
        }

        @keyframes flyin{
            from{ transform: translateY(100%); opacity:0; }
        }

    </style>

    <div class="container">{{ form(articleForm) }}</div>
{% endblock %}